source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '3.2.0'

gem 'crichton', git: 'git@github.com:mdsol/crichton.git', branch: 'develop' #FIXME
gem 'representors', git: 'git@github.com:mdsol/representors.git', branch: 'develop' #FIXME

gem 'launchy'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'rack'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'nokogiri'

# gem 'ffi-rzmq',  '~> 2.0.1' Uncomment to use zeromq
gem 'yajl-ruby'
gem 'faraday'

group :test, :development do
  gem 'debugger',       '~> 1.6.4'
end

group :test do
  gem 'webmock',        '~> 1.13.0'
  gem 'equivalent-xml', '~> 0.3.0'
  gem 'rspec',          '~> 2.13.0'
  gem 'simplecov',      '~> 0.7.1'
end

